### ISSUE TITLE
Links to dataset used?

### ISSUE THREAD

**Issue by vishaal27** [shikiw/DAM-VP#1]
Hi,

Thanks for the amazing work! Would it be possible to share the link for downloading/acquiring your Fru92 and Veg200 data splits? I see that the original dataset is here: https://github.com/ustc-vim/vegfru, but I would like to know the exact processing you've performed on the dataset to get to the two subsets you've used.

Thanks!

**Comment by shikiw** [comment]
Hi, 

We follow the official split of VegFru. You can see the following files or dictionaries after downloading the dataset at ```data/finegrained_dataset/vegfru-dataset```,
- fru92_images/  
- fru92_lists/  
- supvegfru_test.txt  
- supvegfru_train.txt  
- supvegfru_val.txt  
- veg200_images/  
- veg200_lists/  
- vegfru_test.txt  
- vegfru_train.txt  
- vegfru_val.txt

Our processing code can be found at:
- https://github.com/shikiw/DAM-VP/blob/8f29f760b091ec3256e82b26ce4a76f82f979926/data_utils/datasets/fru92/txt_dataset.py
- https://github.com/shikiw/DAM-VP/blob/8f29f760b091ec3256e82b26ce4a76f82f979926/data_utils/datasets/veg200/txt_dataset.py

We hope these will be helpful for you!

**Comment by vishaal27** [comment]
Thanks!
