### ISSUE TITLE
What kind of GPUs are needed?

### ISSUE THREAD

**Issue by hlyf-xs** [shikiw/DAM-VP#3]
Hi, This is a good job, but I want to know what kind of GPUs are needed for training.

**Comment by shikiw** [comment]
Thanks! We use RTX A6000-48G.

**Comment by hlyf-xs** [comment]
Only one?
&nbsp;


海浪一方
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年5月30日(星期二) 中午11:45
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [shikiw/DAM-VP] What kind of GPUs are needed? (Issue #3)





 
Thanks! We use RTX A6000-48G.

**Comment by shikiw** [comment]
Yes, it is enough.
