### ISSUE TITLE
Missing json files about train split

### ISSUE THREAD

**Issue by xing0047** [shikiw/DAM-VP#4]
Hi,

Thanks for your excellent work and contributions of open-sourced code.

I think there should be a bunch of json files claiming the train/test splits of downstream datasets. I met this issue when I run
```
    cd task_adapting
    CUDA_VISIBLE_DEVICES=1 python main.py \
        --base_dir ../data \
        --pretrained_model vit-b-1k \
        --adapt_method prompt_wo_head \
        --test_dataset 'cub200' \
        --epochs 50 \
        --lr 50000 \
        --weight_decay 0.0 \
        --checkpoint_dir ../meta-training/checkpoints/vit-b-1k-wo-head.pth
```

The error seems lie in a class named 'JSONDataset', which needs 'train.json' to continue training.

Thanks for your efforts.

**Comment by shikiw** [comment]
Hi, 

We use the same data split as VPT. You can find these json files at the data resources provided in [VPT](https://github.com/KMnP/vpt) repo.

**Comment by xing0047** [comment]
Thanks. I will close the issue.
